language: emacs-lisp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cabal-install
  - cabal update
  - cabal install ghc-mod-$GHC_MOD_VERSION
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
  - GHC_MOD_VERSION=4.1.0
script:
  - emacs --version
  - make test
